### ISSUE TITLE
Update Table's Column lengths can be wrong for Char Set CHAR_CS?

### ISSUE THREAD

**Issue by stewstryker** [antonscheffer/Excel2APEX#3]
I noticed when mapping my spreadsheet columns to my Oracle table that the CHAR and VARCHAR2 column lengths are always 3 times the size in the database.  Please see the attached screenshot.

I **believe** that's because the query that gets the column types uses the `data_length` column instead of the `char_length` column. All the columns in our tables have a character_set_name of 'CHAR_CS', but I don't know enough about that to know if it's significant.

Thanks for the cool utility!

![Screenshot and table definition](https://user-images.githubusercontent.com/25345417/140570982-f38e3eee-3a4f-440b-8958-7f71f2dc910f.png)

**Comment by antonscheffer** [comment]
It's only used for "describing" the selected table, so this should not cause any problems in the working of the plugin.

**Comment by antonscheffer** [comment]
I will fix this in the next update of the plugin.

**Comment by stewstryker** [comment]
Thanks for agreeing this was an issue, though only cosmetic. 

**Not** to push, but do you have a rough idea when the next release might be?

Just this morning I starting building another page that will use your plug-in to load a different table. This is so much faster and more flexible than the built-in Apex Data Loader Wizard, at least the one in Apex 19c that we're using.

Thanks again,

Stew

**Comment by antonscheffer** [comment]
Will not be this year, if ever. As long as this cosmetic issue is the only thing which needs to be changed I will not start.
I have other issues with a higher priority on my to do list, like bugs in [as_sftp](https://github.com/antonscheffer/as_sftp) or rewriting as_xlsx for modern Oracle versions (> 12.2)

**Comment by stewstryker** [comment]
Thanks for the reply and I completely understand not digging into this just
for that minor issue.

If it's easy, could you please point me generally to where that code block
is, so I can try to resolve it myself? I'm experienced in Oracle, but still
light in my JS skills. I've looked through the Oracle package and the
Javascript file, but can't find where the table column length is calculated
from the *all_tab_cols *or *all_tab_columns *tables.


If you're interested, I noticed another intermittent cosmetic issue. I
hadn't reported it because I couldn't replicate it consistently.

After selecting the Load File, the pop-up column-mapping window doesn't
always size correctly. That is, sometimes it's only about 350 pixels high,
when it should be much taller to accommodate the number of target columns
in the table. I normally work in Chrome and I'm seeing it there. I haven't
tried to replicate it in another browser.


All the best,

Stew

**Comment by antonscheffer** [comment]
It’s not using all_tab_columns but dbms_sql.describe_columns2. That procedure populates a record which only has a attribute col_max_len. That is the length in bytes, not in chars.

**Comment by stewstryker** [comment]
Thanks!

Stew
